services:
  influxdb:
    image: influxdb:2.7
    container_name: influxdb_jh
    ports:
      - "${INFLUXDB_PORT}:8086"
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=adminpassword
      - DOCKER_INFLUXDB_INIT_ORG=${INFLUXDB_ORG}
      - DOCKER_INFLUXDB_INIT_BUCKET=${INFLUXDB_BUCKET}
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=${INFLUXDB_TOKEN}
    volumes:
      - ${DATA_PATH}/influxdb/data:/var/lib/influxdb2
      - ${DATA_PATH}/influxdb/config:/etc/influxdb2
    networks:
      - jh-network
    restart: always
