services:
  grafana:
    image: grafana/grafana:latest
    container_name: grafana_jh
    ports:
      - "${GRAFANA_PORT}:3000"
    volumes:
      - ${DATA_PATH}/grafana/data:/var/lib/grafana
      - ./provisioning:/etc/grafana/provisioning:ro
    environment:
      - INFLUXDB_ORG=${INFLUXDB_ORG}
      - INFLUXDB_BUCKET=${INFLUXDB_BUCKET}
      - INFLUXDB_TOKEN=${INFLUXDB_TOKEN}
    networks:
      - jh-network
    depends_on:
      - influxdb
    restart: always
