services:
  nginx:
    image: nginx:latest
    container_name: nginx_jh_8081
    ports:
      - "${NGINX_PORT}:80"
    volumes:
      - ./conf/nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - jh-network
    restart: always
